### ISSUE TITLE
How to download data with formulas?

### ISSUE THREAD

**Issue by sarah-allec** [vstanev1/Supercon#1]
Hello,

I am wondering how we can download data from the SuperCon website that includes the formula name also (i.e., would include (Ba,La)2CuO4 in addition to Ba0.2La1.8Cu1O4-Y).

Thank you!

**Comment by vstanev1** [comment]
Dear Sarah,

I don't think you can do that from Supercon. There used to be a simple
"Download" option, which gave you the the chemical formula (e.g., "
Ba0.2La1.8Cu1O4-Y") and separately the individual elements ("Ba", "La",
etc.) in addition to "Tc" but even that is no longer possible.

Best,
Valentin

**Comment by sarah-allec** [comment]
Dear Valentin,

Thank you so much!

Sarah
